version: "3"

services:

  ckan:
    container_name: ckan-${PROJECT_NUMBER}
    restart: unless-stopped
    build:
      context: ckan/
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CKAN_SITE_URL=${DEFAULT_URL}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKANEXT__XLOADER__JOBS_DB__URI=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
    depends_on:
      - db
      - solr
      - redis
    volumes:
      - ckan_storage:/var/lib/ckan

  db:
    container_name: db-${PROJECT_NUMBER}
    restart: unless-stopped
    build:
      context: postgresql/
      args:
        - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DATASTORE_READONLY_PASSWORD=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=${TZ}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-ckan}", "-d", "${POSTGRES_DB:-ckan}"]
     
  solr:
    container_name: solr${PROJECT_NUMBER}
    image: ckan/ckan-solr:2.9-solr8
    restart: unless-stopped
    volumes:
      - solr_data:/var/solr
    environment:
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/"]

  redis:
    container_name: redis${PROJECT_NUMBER}
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]

volumes:
  ckan_storage:
  pg_data:
  solr_data:

