version: "3"

services:

  nginx:
    container_name: nginx-${PROJECT_NUMBER}
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    build:
      context: nginx/
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:${NGINX_PORT}:80"
    environment:
      - TZ=${TZ}
    networks:
      - nginx_db_network

networks:
  nginx_db_network:
    external: true